#-------------------------------
# General Site Settings
title: Seoyeon An
logo: logo.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Seoyeon An
  image: sy_210.jpg
  say-hello: Hello, I’m <strong>Seoyeon An</strong>
  bio: Bachelor's Degree in Yonsei Univ. Applied Statistics

#-------------------------------
# Contact links
twitter: Null
facebook: https://www.facebook.com/profile.php?id=100012461476819 # Add your Facebook handle
dribbble: Null # Add your Dribbble handle
instagram: https://www.instagram.com/yeonii__a18_/ # Add your Instagram handle
pinterest: Null # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: seoyeon # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: yeonii__a18_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
